version: "3.7"

services:

  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_USER: boatyard
      POSTGRES_PASSWORD: test_db_password
    ports:
      - '5434:5432'
    volumes:
      - boatyard-postgres:/var/lib/postgresql/data
  boatyard:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    depends_on:
      - postgres
    volumes:
      - type: bind
        source: ./boatyard_api
        target: /opt/app/boatyard_api
    command: bundle exec puma -C config/puma.rb
    ports:
      - '3000:3000'
    env_file:
      - .env
    stdin_open: true
    tty: true
volumes:
  boatyard-postgres:
